query Activities {
    activities: allActivities {
        edges {
            node {
                name
                submissionDate
                submissionState
            }
        }
    }
}